FROM mysql:8.0
SHELL ["/bin/bash", "-oeux", "pipefail", "-c"]

ENV TZ=Asia/Tokyo
ENV MYSQL_ROOT_PASSWORD=samplepassword
ENV MYSQL_DATABASE=sampledb
ENV MYSQL_USER=sampleuser
ENV MYSQL_PASSWORD=samplepassword
